CREATE TABLE `Users` (
     `userId` BIGINT NOT NULL AUTO_INCREMENT,
     `name` VARCHAR(100) NOT NULL,
     `email` VARCHAR(100) NOT NULL,
     `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     CONSTRAINT `PK_USERS` PRIMARY KEY (`userId`)
);

CREATE TABLE `Schedules` (
     `scheduleId` BIGINT NOT NULL AUTO_INCREMENT,
     `content` VARCHAR(500) NOT NULL,
     `password` VARCHAR(100) NOT NULL,
     `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
     `updatedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
     `userId` BIGINT NOT NULL,
     CONSTRAINT `PK_SCHEDULES` PRIMARY KEY (`scheduleId`),
     CONSTRAINT `FK_SCHEDULE_USER` FOREIGN KEY (`userId`) REFERENCES `Users`(`userId`) ON DELETE CASCADE
);